### ISSUE TITLE
"Strategy" should choose the measure based on both the available space and the road cost.

### ISSUE THREAD

**Issue by Carsopre** [Deltares/Koswat#169]
We currently provide the `Koswat` analysis with a clustering strategy that determines which reinforcement can be applied based on its cost and the available space. Since the introduction of infrastructures we need to extend the strategy so that it also considers the direct costs of modifying any affected infrastructure.

**What needs to be done?**
- Extend the current strategy logic so that the location - profile costs also include the ones of infrastructures.
   - Adapt if needed the way we collect the `InfrastructureLocationProfileCostReport` (currently in just a list), we might need to cluster them by introducing a hierarchy as we do already for the profile reports.
- Extend the related report so that these costs are reflected.
- Extend the existing documentation with the new "infrastructure" addition.

**Acceptance criteria**
- Acceptance test results are validated with PO.
- Documentation is updated accordingly.
- Reference data is updated.

**Comment by peterdgr** [comment]
**What needs to be solved**
Currently the strategy choosing the optimal measure is only based on the space available due to obstacles. This might lead to a solution that is cheaper because of less infrastructure cost although the measure itself is more expensive.

**Solution approach**
Add new strategy (based on cost) that tries to upgrade clusters generated by the existing strategy (based on space) to a higher measure that could be cheaper due to infra cost.
This becomes the default strategy which uses the original one, which remains untouched and is (for now) only reachable by code.

**Acceptance criteria**
- Tests have been adjusted and approved
- Documentation is extended and approved

**Opportunities for improvement/extension**
- More output of intermediate results (output of different strategies)
- Config settings to define the strategies to be applied
- Omit certain measures based on cost/Euro (e.g. VPS is more expensive)
- More fine-grained approach (e.g. creating subclusters)
- Base strategy on cifferent order (create clusters based on infra and only after that look at space available)

**Comment by Carsopre** [comment]
All subissues have been closed, agreed to close.
